### ISSUE TITLE
Sbt can't find nd4j-native-platform

### ISSUE THREAD

**Issue by Jydago** [deeplearning4j/nd4j#1147]
When trying to get the dependency for nd4j, sbt can't seem to find 
"org.nd4j" % "nd4j-native-platform" % "0.4.0"
even though it exists on sonatype.

I'm working on windows 10, trying to build it both through IntelliJ and directly in sbt, but gives the same stack trace in both cases.
Stack trace: https://gist.github.com/Jydago/9cd210ff6cc69a5a6b220d4dfd3b4f29
build.sbt: https://gist.github.com/Jydago/4765c069277764817c4da7ef3b23e170

**Comment by saudet** [comment]
Do you get the same error building nd4s? I cannot reproduce this error building nd4s on my machine.

If nd4s also builds fine for your machine, could you provide a small sample project (as a gist) to reproduce this error?

**Comment by Jydago** [comment]
When you say build nd4s, do you mean to add "org.nd4j" % "nd4s_2.11" % "0.4.0" into my build.sbt?

**Comment by saudet** [comment]
It should do the same thing, but what about `git clone https://github.com/deeplearning4j/nd4s/ && sbt build`?

**Comment by Jydago** [comment]
sbt compile gives this https://gist.github.com/Jydago/e0c2aa55612c7b28c67298192f08378c

**Comment by saudet** [comment]
`download failed: org.nd4j#nd4j-native;0.4.0!nd4j-native.jar` -> You sbt isn't configured properly. Please configure it properly to let is download from the Maven central and try again.

**Comment by Jydago** [comment]
I don't think I have configured anything about sbt before, so what kind of configurations are you thinking of?

**Comment by saudet** [comment]
sbt by default will download from the Maven central. You changed something settings that prevents from happening. So undo everything that you did in the past, and it will work.

**Comment by saudet** [comment]
Or maybe you're using an old version of sbt? That's another possibility. What does `sbt about` returns?

**Comment by Jydago** [comment]
sbt 0.13.11

**Comment by saudet** [comment]
Works fine with sbt 0.13.12 here. Maybe some bugs were fixed. Could you try with 0.13.12?

**Comment by Jydago** [comment]
Still the same problem <.<... I can't think of any changes that I have done in sbt.

**Comment by saudet** [comment]
Maybe it's a Windows-only bug. Can you say if it happens on Linux?

**Comment by Jydago** [comment]
I can try it on the build server, which is a linux server, but will have to wait until tomorrow to get access to it.

**Comment by saudet** [comment]
Looks like there was an issue with building on Windows after all. I got a different set of weird errors, but this commit fixes `sbt compile` on Windows: https://github.com/deeplearning4j/nd4s/commit/800df7c90b4027abe1d12ce9d8adcdbff1e570b3
Now it builds fine for me on Windows as well. Let us know if you still have issues with that.
