### ISSUE TITLE
Cuda MemcpyAsync failed

### ISSUE THREAD

**Issue by Jajawah** [deeplearning4j/nd4j#1255]
Hi,

running this code rises a bug with cuda backend, not with native.
```
int a=9;
int b=2;
int[] shapes = new int[a];
for (int i = 0; i < a; i++) {
	shapes[i] = b;
}
INDArray c = Nd4j.linspace(1, (int) (100 * 1 + 1 + 2), (int) Math.pow(b, a)).reshape(shapes);
c=c.sum(0);
double[] d = c.data().asDouble();
```
if I remove the `c=c.sum(0);` then no more bug...

Conf : 0.5.1-SNAPSHOT on ubuntu 16.04
```
CUDA error at /home/***/git/libnd4j/blas/cuda/NativeOps.cu:5235 code=77(<unknown>) "result" 
CUDA error at /home/***/git/libnd4j/blas/cuda/NativeOps.cu:5194 code=77(<unknown>) "result" 
Exception in thread "main" java.lang.IllegalStateException: MemcpyAsync failed: AllocationShape(offset=0, length=256, stride=1, elementSize=8, dataType=DOUBLE)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.synchronizeToHost(SynchronousFlowController.java:56)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.synchronizeThreadDevice(CudaZeroHandler.java:1162)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.synchronizeHostData(AtomicAllocator.java:309)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.asDouble(BaseCudaDataBuffer.java:822)
	at ...
Failed on [73419198464] -> [34434232320], size: [2048], direction: [2], result: [77]
```

**Comment by raver119** [comment]
You've probably forgot to add that you're using DOUBLE as dataType, am i right?

**Comment by Jajawah** [comment]
right !
```
real.class.double = org.nd4j.linalg.jcublas.JCublasNDArray
complex.class.double = org.nd4j.linalg.jcublas.complex.JCublasComplexNDArray
dtype = double
complex.double.class = org.nd4j.linalg.jcublas.complex.ComplexDouble
complex.float.class = org.nd4j.linalg.jcublas.complex.ComplexFloat
blas.ops= org.nd4j.linalg.jcublas.JCublasWrapper
ndarrayfactory.class = org.nd4j.linalg.jcublas.JCublasNDArrayFactory
affinitymanager = org.nd4j.jita.concurrency.CudaAffinityManager
ndarray.order = c
databufferfactory = org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory
shapeinfoprovider = org.nd4j.linalg.jcublas.CachedShapeInfoProvider
constantsprovider = org.nd4j.jita.constant.CudaConstantHandler
ndarray.copyops = true
opexec= org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner
resourcemanager_state = true
alloc = direct
fft = org.nd4j.linalg.jcublas.fft.JcudaFft
opexec.mode= native
```

**Comment by raver119** [comment]
Fixed, thanks for highlighting this one.

Will be merged tomorrow hopefully.

**Comment by raver119** [comment]
As for workaround, two options available:

1) Temporary use FLOAT datatype
2) build from libnd4j/nd4j r119_mGRD branches.

**Comment by DuaneNielsen** [comment]
I also found increasing the amount of memory configured helps.  Although it did not solve the underlying problem, it definitely helped my software run for longer.

	Nd4j.create(1);
	Configuration config = CudaEnvironment.getInstance().getConfiguration();
	    config.setMaximumDeviceCacheableLength(1024 * 1024 * 1024L)
	    .setMaximumDeviceCache(4L * 1024 * 1024 * 1024L)
	    .setMaximumHostCacheableLength(1024 * 1024 * 1024L)
	    .setMaximumHostCache(4L * 1024 * 1024 * 1024L);
