### ISSUE TITLE
nd4j-native gemm_driver.constprop failure on ppc64le

### ISSUE THREAD

**Issue by mtvars** [deeplearning4j/nd4j#1355]
dl4j-examples fail on Power8 machine with Ubuntu 16.04 LTS (GNU/Linux 4.4.0-31-generic ppc64le)
and java 1.8

Problematic frame:
C  [libopenblas.so.0+0x16edd0]  gemm_driver.constprop.0+0x2c0

[hs_err_pid23138.txt](https://github.com/deeplearning4j/nd4j/files/550714/hs_err_pid23138.txt)

**Comment by agibsonccc** [comment]
@saudet

**Comment by saudet** [comment]
It'll be hard to debug without a machine here..

**Comment by mtvars** [comment]
Do you think it could be a problem of OpenBlas? Could I try a different backend like ATLAS?
I need some guidance on how to do that however..

**Comment by raver119** [comment]
No, i'm pretty sure this issue is tied with similar issue raised on mac spark few days. ago.

**Comment by saudet** [comment]
Might be fixed in OpenBLAS 0.2.19...

**Comment by raver119** [comment]
How long it takes to run example till crash? Is crash 100% reproducible?

**Comment by mtvars** [comment]
Yes it is 100% reproducible.
It crashes the first time a gemm function is called. 
For example, in the feedforward mnist example, it crashes during the first layer activation, function sgemm() in nd4j-native-0.6.0.jar!/org/nd4j/linalg/cpu/nativecpu/blas/CpuLevel3.class

**Comment by raver119** [comment]
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/mnist/MLPMnistSingleLayerExample.java

This particular example, does it reproduces crash for you?

**Comment by mtvars** [comment]
This is the example I'm talking about.

**Comment by raver119** [comment]
Great. Now please set  OMP_NUM_THREADS environment variable to 1, and run example again.

p.s. `export OMP_NUM_THREADS=1`

**Comment by mtvars** [comment]
Now it is no longer 100% reproducible. It ran successfully once but usually it fails at some random iteration with this message:

Problematic frame:
C [libopenblas.so.0+0x246d70]  sgemm_beta+0xb0

**Comment by raver119** [comment]
Very interesting.

Could you please build libdn4j/nd4j/dl4j from current master branches then, and check if problem still reproducible using 0.6.1-SNAPSHOT?

**Comment by mtvars** [comment]
With 0.6.1-SNAPSHOT the behavior is the same as my last comment (sgemm_beta failure at some random iteration).
Only difference is that now it has the same behavior regardless of OMP_NUM_THREADS value.

**Comment by raver119** [comment]
Aha, that might be considered good news.

1 нояб. 2016 г. 17:22 пользователь "mtvars" <notifications@github.com>
написал:

**Comment by raver119** [comment]
Please pull latest libnd4j master, and run the same example once again.

**Comment by raver119** [comment]
I mean, please pull all latest master branches, rebuild everything and run example :)

**Comment by mtvars** [comment]
Unfortunately, nothing changed...

**Comment by raver119** [comment]
Thank you, we'll keep digging.

**Comment by saudet** [comment]
@mtvars How are you building OpenBLAS? Could you try to build it with this cppbuild.sh script?
https://github.com/bytedeco/javacpp-presets/blob/master/openblas/cppbuild.sh

**Comment by raver119** [comment]
Pull latest masters once again, and run once again please.

**Comment by saudet** [comment]
I could reproduce this behavior with a machine from [SuperVessel](https://ny1.ptopenlab.com/dashboard/project/) (accounts are free). Been trying things the whole day, but wasn't able to find the cause. It looks like DL4J is unusable on Power hardware because of that. Leaving Valgrind running overnight and we will see if it catches anything.

**Comment by raver119** [comment]
Omg, thanks! 
I will get there asap!

**Comment by raver119** [comment]
Issue should be fixed on current master. Please check (if possible) and confirm/decline.

Now none of the examples are crashing for me on ppc64le machine running ubuntu 14.04

**Comment by mtvars** [comment]
On ubuntu 16.04, it still crashes. 
However, I have not yet tried saudet's suggestion for building OpenBLAS. 
I will do it and inform you.

**Comment by raver119** [comment]
Please post recent crash log (that hs_err_pidXXXXX.log).

**Comment by mtvars** [comment]
[hs_err_pid9409.txt](https://github.com/deeplearning4j/nd4j/files/575623/hs_err_pid9409.txt)

**Comment by raver119** [comment]
Just to be clear, its 100% reproducible for you, right? Each time you run example - it crashes, right?

**Comment by mtvars** [comment]
Correct. 
The first time I used 0.6.1-SNAPSHOT, it was 99% reproducible.
Now it is 100%, but I did not run the examples many times.

**Comment by mtvars** [comment]
Can you please confirm that if you change Layer(0) activation function from "relu" to "sigmoid" (line 71)
in example
../feedforward/mnist/MLPMnistSingleLayerExample.java

it still runs OK for you?

**Comment by raver119** [comment]
Since you're running that on x server, could you please run this particular nd4j test:

https://github.com/deeplearning4j/nd4j/blob/ed4ae3c2691994a0cfa31ac081aeb972f4676fe7/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/crash/CrashTest.java

To launch that thing you should do the following:
```
cd FolderWhereNd4jWasCloned
cd nd4j-backends/nd4j-backend-impls/nd4j-native
mvn clean test -Dtest=org.nd4j.linalg.crash.CrashTest
```

**Comment by mtvars** [comment]
The test was successful. 
Also I should note that all the nd4j-examples run OK.

**Comment by raver119** [comment]
Re: sigmoid, on x86_64 sigmoid change works fine. Checking on ppc64 now

**Comment by raver119** [comment]
Same result, runs fine.

Please show me full output log prior to crash.

**Comment by mtvars** [comment]
You mean this?

[output_log.txt](https://github.com/deeplearning4j/nd4j/files/576016/output_log.txt)

**Comment by raver119** [comment]
Yes, exactly.

I've just built OpenBLAS from sources now, and i see pretty much the same crush you're reporting.

**Comment by mtvars** [comment]
But I have not built OpenBLAS from sources. I installed through apt-get ubuntu libopenblas-dev which installs libopenblas_power8p-r0.2.18.so
What version of OpenBLAS works OK for you?

**Comment by raver119** [comment]
Hold on there, it just crashes for me with primitive things, like x.mmul(y,z). Without strides or anything.
And works fine without openblas (default libblas). However on linux/windows openblas works fine for me. So i'm investigating what's wrong there.

**Comment by raver119** [comment]
As i see this user reports this crash for the same openblas version i've used
https://groups.google.com/forum/#!topic/openblas-users/4WLiz0w42As

**Comment by raver119** [comment]
So, the best thing i could think of here, is to provide basic GEMM implementation, and make it default temporary for power8, until OpenBLAS gets fixed.

Prototype works now, and nothing crashes.

**Comment by raver119** [comment]
Please pull & rebuld latest masters, temporary workaround was applied.

**Comment by saudet** [comment]
I've figured out a patch that works, and it's now in the presets. Enjoy!

**Comment by mtvars** [comment]
Now the examples are working!
Thanks a lot for your efforts!!
