### ISSUE TITLE
ClosedByInterruptException in org.nd4j.linalg.api.buffer.BaseDataBuffer

### ISSUE THREAD

**Issue by dnaase** [deeplearning4j/nd4j#1509]
Hi,
I am using nd4j-0.7.0 and run deeplearning4j at spark, the training is still going on, but keep going to throw RuntimeException. Here is the warning msg:

Caused by: java.lang.RuntimeException: java.nio.channels.ClosedByInterruptException
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.readContent(BaseDataBuffer.java:1317)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.read(BaseDataBuffer.java:1274)
	... 10 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:293)
	at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileInputStream.seek(RawLocalFileSystem.java:108)
	at org.apache.hadoop.fs.BufferedFSInputStream.seek(BufferedFSInputStream.java:89)
	at org.apache.hadoop.fs.FSDataInputStream.seek(FSDataInputStream.java:63)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.readChunk(ChecksumFileSystem.java:228)
	at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:275)
	at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:227)
	at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:195)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:388)
	at java.io.DataInputStream.readFloat(DataInputStream.java:446)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.readContent(BaseDataBuffer.java:1291)
	... 11 more
Completed Epoch {}19

**Comment by raver119** [comment]
Please try latest version 0.7.1.

15 дек. 2016 г. 14:20 пользователь "Yaping Liu" <notifications@github.com>
написал:

**Comment by AlexDBlack** [comment]
Right, this should have been fixed as of 0.7.1 here:
https://github.com/deeplearning4j/deeplearning4j/pull/2345

**Comment by dnaase** [comment]
I still get the same error when using 0.7.1 from maven now.
Here is my part of pom.xml:

	
	<dependency>
		<groupId>org.deeplearning4j</groupId>
		<artifactId>deeplearning4j-core</artifactId>
		<version>0.7.1</version>
	</dependency>
	<dependency>
		<groupId>org.deeplearning4j</groupId>
		<artifactId>deeplearning4j-nn</artifactId>
		<version>0.7.1</version>
	</dependency>
	<dependency>
		<groupId>org.deeplearning4j</groupId>
		<artifactId>dl4j-spark_2.10</artifactId>
		<version>0.7.1</version>
	</dependency>
	<dependency>
		<groupId>org.nd4j</groupId>
		<artifactId>nd4j-native</artifactId>
		<version>0.7.1</version>
	</dependency>
	<dependency>
		<groupId>org.nd4j</groupId>
		<artifactId>nd4j-api</artifactId>
		<version>0.7.1</version>
	</dependency>
	<dependency>
		<groupId>org.nd4j</groupId>
		<artifactId>nd4j-base64</artifactId>
		<version>0.7.1</version>
	</dependency>
	<dependency>
		<groupId>org.nd4j</groupId>
		<artifactId>nd4j-kryo_2.10</artifactId>
		<version>0.7.1</version>
	</dependency>

**Comment by raver119** [comment]
Post full pom.xml please as gist

15 дек. 2016 г. 14:56 пользователь "Yaping Liu" <notifications@github.com>
написал:

**Comment by AlexDBlack** [comment]
Another thing to test with 0.7.1: disable async prefetching using ```.workerPrefetchNumBatches(0)``` in the ParameterAveragingTrainingmaster configuration.

**Comment by dnaase** [comment]
Error details are actually changed in 0.7.1 even with the same top RuntimeException (now in readUnknown):

java.lang.RuntimeException: java.lang.RuntimeException: java.nio.channels.ClosedByInterruptException
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.read(BaseDataBuffer.java:1279)
	at org.nd4j.linalg.compression.CompressedDataBuffer.readUnknown(CompressedDataBuffer.java:79)
	at org.nd4j.linalg.factory.Nd4j.read(Nd4j.java:2296)
	at org.nd4j.linalg.dataset.DataSet.load(DataSet.java:398)
	at org.deeplearning4j.spark.iterator.PathSparkDataSetIterator.load(PathSparkDataSetIterator.java:164)
	at org.deeplearning4j.spark.iterator.PathSparkDataSetIterator.next(PathSparkDataSetIterator.java:130)
	at org.deeplearning4j.spark.iterator.PathSparkDataSetIterator.next(PathSparkDataSetIterator.java:24)
	at org.deeplearning4j.datasets.iterator.IteratorDataSetIterator.next(IteratorDataSetIterator.java:57)
	at org.deeplearning4j.datasets.iterator.IteratorDataSetIterator.next(IteratorDataSetIterator.java:43)
	at org.deeplearning4j.datasets.iterator.IteratorDataSetIterator.next(IteratorDataSetIterator.java:18)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$IteratorRunnable.run(AsyncDataSetIterator.java:303)
Caused by: java.lang.RuntimeException: java.nio.channels.ClosedByInterruptException
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.readContent(BaseDataBuffer.java:1317)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.read(BaseDataBuffer.java:1274)
	... 10 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:293)
	at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileInputStream.seek(RawLocalFileSystem.java:108)
	at org.apache.hadoop.fs.BufferedFSInputStream.seek(BufferedFSInputStream.java:89)
	at org.apache.hadoop.fs.FSDataInputStream.seek(FSDataInputStream.java:63)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.readChunk(ChecksumFileSystem.java:228)
	at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:275)
	at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:227)
	at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:195)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:388)
	at java.io.DataInputStream.readFloat(DataInputStream.java:446)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.readContent(BaseDataBuffer.java:1291)
	... 11 more

**Comment by raver119** [comment]
What about pom.xml? Can we see full version of it?

**Comment by dnaase** [comment]
<project>
	<build>
  <plugins>
    <plugin>
      <artifactId>maven-assembly-plugin</artifactId>
      <configuration>
        <archive>
          <manifest>
            <mainClass>main.java.edu.mit.compbio.ccinference.testCode</mainClass>
          </manifest>
        </archive>
        <descriptorRefs>
          <descriptorRef>jar-with-dependencies</descriptorRef>
        </descriptorRefs>
      </configuration>
    </plugin>
  </plugins>
</build>
	
	<groupId>edu.mit.compbio</groupId>
  <artifactId>testCode</artifactId>
  <modelVersion>4.0.0</modelVersion>
  <name>testCode</name>
  <packaging>jar</packaging>
  <version>0.38</version>

  <repositories>
    <repository>
        <id>jsi</id>
        <url>http://repo.springsource.org/libs-release-remote</url>
    </repository>
</repositories>

 <dependencies>
  	<dependency>
      <groupId>args4j</groupId>
      <artifactId>args4j</artifactId>
      <version>2.0.31</version>
    </dependency>
	<dependency>
		<groupId>com.github.samtools</groupId>
		<artifactId>htsjdk</artifactId>
		<version>1.141</version>
	</dependency>
	<dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-math3</artifactId>
		<version>3.3</version>
	</dependency>
	<dependency>
		<groupId>log4j</groupId>
		<artifactId>log4j</artifactId>
		<version>1.2.17</version>
	</dependency>
	<dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-lang3</artifactId>
		<version>3.4</version>
	</dependency>
	<dependency>
		<groupId>org.biojava</groupId>
		<artifactId>biojava-genome</artifactId>
		<version>4.1.0</version>
	</dependency>
	
	<dependency>
		<groupId>org.biojava</groupId>
		<artifactId>biojava-core</artifactId>
		<version>4.2.4</version>
	</dependency>
	
	<dependency>
		<groupId>org.ujmp</groupId>
		<artifactId>ujmp-core</artifactId>
		<version>0.3.0</version>
	</dependency>
	
	<dependency>
		<groupId>be.ac.ulg.montefiore.run.jahmm</groupId>
		<artifactId>jahmm</artifactId>
		<version>0.6.2</version>
	</dependency>
	<dependency>
		<groupId>it.unimi.dsi</groupId>
		<artifactId>fastutil</artifactId>
		<version>7.0.8</version>
	</dependency>

   <dependency> 
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-core_2.10</artifactId>
      <version>1.6.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-mllib_2.10</artifactId>
      <version>1.6.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-sql_2.10</artifactId>
      <version>1.6.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
       <groupId>ai.h2o</groupId>
       <artifactId>sparkling-water-core_2.10</artifactId>
       <version>1.6.8</version>
     </dependency>
     <dependency>
      <groupId>ai.h2o</groupId>
      <artifactId>h2o-algos</artifactId>
      <version>3.10.0.10</version>
     </dependency>
	<dependency>
		<groupId>ai.h2o</groupId>
		<artifactId>h2o-core</artifactId>
		<version>3.10.0.10</version>
	</dependency>
     <dependency>
       <groupId>ai.h2o</groupId>
       <artifactId>h2o-scala_2.10</artifactId>
       <version>3.10.0.10</version>
     </dependency>

	
	<dependency>
		<groupId>org.deeplearning4j</groupId>
		<artifactId>deeplearning4j-core</artifactId>
		<version>0.7.1</version>
	</dependency>
	<dependency>
		<groupId>org.deeplearning4j</groupId>
		<artifactId>deeplearning4j-nn</artifactId>
		<version>0.7.1</version>
	</dependency>
	<dependency>
		<groupId>org.deeplearning4j</groupId>
		<artifactId>dl4j-spark_2.10</artifactId>
		<version>0.7.1</version>
	</dependency>
	<dependency>
		<groupId>org.nd4j</groupId>
		<artifactId>nd4j-native</artifactId>
		<version>0.7.1</version>
	</dependency>
	<dependency>
		<groupId>org.nd4j</groupId>
		<artifactId>nd4j-api</artifactId>
		<version>0.7.1</version>
	</dependency>
	<dependency>
		<groupId>org.nd4j</groupId>
		<artifactId>nd4j-base64</artifactId>
		<version>0.7.1</version>
	</dependency>
	<dependency>
		<groupId>org.nd4j</groupId>
		<artifactId>nd4j-kryo_2.10</artifactId>
		<version>0.7.1</version>
	</dependency>
	<dependency>
		<groupId>org.broadinstitute.gatk</groupId>
		<artifactId>gatk-package-distribution</artifactId>
		<version>3.3</version>
		<scope>system</scope>
		<systemPath>${basedir}/lib/gatk-package-distribution-3.3.jar</systemPath>
	</dependency>
	<dependency>
		<groupId>edu.unc.genomics</groupId>
		<artifactId>java-genomics-io</artifactId>
		<version>1.0</version>
		<scope>system</scope>
		<systemPath>${basedir}/lib/java-genomics-io.jar</systemPath>
	</dependency>
		<dependency>
		<groupId>jdistlib</groupId>
		<artifactId>jdistlib</artifactId>
		<version>0.4.4</version>
		<scope>system</scope>
		<systemPath>${basedir}/lib/jdistlib-0.4.4-bin.jar</systemPath>
	</dependency>
	<dependency>
		<groupId>ch.systemsx.cisd.hdf5</groupId>
		<artifactId>sis-jhdf5-batteries_included</artifactId>
		<version>1.0</version>
		<scope>system</scope>
		<systemPath>${basedir}/lib/sis-jhdf5-batteries_included.jar</systemPath>
	</dependency>
  </dependencies>
</project>

**Comment by dnaase** [comment]
[pom.xml.gz](https://github.com/deeplearning4j/nd4j/files/654727/pom.xml.gz)

**Comment by raver119** [comment]
Thanks, pom.xml definitely looks fine. However, we were pretty sure this bug was fixed in 0.7.1...

**Comment by AlexDBlack** [comment]
And, to repeat my previous comment:

Another thing to test with 0.7.1: disable async prefetching using .workerPrefetchNumBatches(0) in the ParameterAveragingTrainingmaster configuration.

Try that and let us know. Basically there's an interrupted exception being thrown *somewhere* in the thread, and there's only a couple of places that can happen... Async prefetching being one of them.

**Comment by raver119** [comment]
@dnaase have you tried Alex's advice?
