### ISSUE TITLE
Bernoulli distribution - broken for CUDA; native P value does not follow convention

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1864]
https://en.wikipedia.org/wiki/Bernoulli_distribution
```
...the Bernoulli distribution... takes the value 1 with probability p and the value 0 with probability q=1-p
```

Looks like we do p = probability of value 0 for native. Looks to always return 0 for CUDA.

```
        int length = 20;
        DecimalFormat df = new DecimalFormat("0.00");
        for(double p=0.0; p<=1.0; p+=0.1){

            INDArray arr = Nd4j.createUninitialized(length);
            Nd4j.getExecutioner().exec(new BernoulliDistribution(arr, p));

            int count = arr.sumNumber().intValue();
            double frac = count / (double)length;
            System.out.println( df.format(p) + "\t\t#1s: " + count + "\t\tFrac 1s: " + df.format(frac));
        }
```

Native:
```
0.00		#1s: 20		Frac 1s: 1.00
0.10		#1s: 17		Frac 1s: 0.85
0.20		#1s: 18		Frac 1s: 0.90
0.30		#1s: 10		Frac 1s: 0.50
0.40		#1s: 11		Frac 1s: 0.55
0.50		#1s: 12		Frac 1s: 0.60
0.60		#1s: 11		Frac 1s: 0.55
0.70		#1s: 7		Frac 1s: 0.35
0.80		#1s: 2		Frac 1s: 0.10
0.90		#1s: 2		Frac 1s: 0.10
1.00		#1s: 0		Frac 1s: 0.00
```

Should have no 1s in the output for p=0, and all 1s in the output for p=1, if we follow the typical convention.

CUDA:
```
o.n.l.j.o.e.CudaExecutioner - Device name: [TITAN X (Pascal)]; CC: [6.1]; Total/free memory: [12884901888]
0.00		#1s: 0		Frac 1s: 0.00
0.10		#1s: 0		Frac 1s: 0.00
0.20		#1s: 0		Frac 1s: 0.00
0.30		#1s: 0		Frac 1s: 0.00
0.40		#1s: 0		Frac 1s: 0.00
0.50		#1s: 0		Frac 1s: 0.00
0.60		#1s: 0		Frac 1s: 0.00
0.70		#1s: 0		Frac 1s: 0.00
0.80		#1s: 0		Frac 1s: 0.00
0.90		#1s: 0		Frac 1s: 0.00
1.00		#1s: 0		Frac 1s: 0.00
```

**Comment by raver119** [comment]
Mmmm the only issue i've found there is wrong prob handling < vs >, that's fixed now. Cross-backends tests added, they pass.

Also, added per-element probabilities option, as Susan asked.

**Comment by raver119** [comment]
P.s. here's tests  https://github.com/deeplearning4j/nd4j/blob/1de1b5325b342b244483b269faee1e3ee4ec4c0c/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/rng/RandomTests.java#L507-L577

**Comment by AlexDBlack** [comment]
Native looks good, but after building latest nd4j/libnd4j, I'm still seeing an issue with CUDA:

```
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 8
o.n.n.Nd4jBlas - Number of threads used for BLAS: 8
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [7.1GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
0.00		#1s: 0		Frac 1s: 0.00
0.10		#1s: 0		Frac 1s: 0.00
0.20		#1s: 6		Frac 1s: 0.30
0.30		#1s: 8		Frac 1s: 0.40
0.40		#1s: 6		Frac 1s: 0.30
0.50		#1s: 10		Frac 1s: 0.50
0.60		#1s: 11		Frac 1s: 0.55
0.70		#1s: 14		Frac 1s: 0.70
0.80		#1s: 17		Frac 1s: 0.85
0.90		#1s: 18		Frac 1s: 0.90
1.00		#1s: 20		Frac 1s: 1.00
```


```
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [7.1GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.o.e.CudaExecutioner - Device name: [TITAN X (Pascal)]; CC: [6.1]; Total/free memory: [12884901888]
0.00		#1s: 20		Frac 1s: 1.00
0.10		#1s: 20		Frac 1s: 1.00
0.20		#1s: 20		Frac 1s: 1.00
0.30		#1s: 20		Frac 1s: 1.00
0.40		#1s: 20		Frac 1s: 1.00
0.50		#1s: 20		Frac 1s: 1.00
0.60		#1s: 20		Frac 1s: 1.00
0.70		#1s: 20		Frac 1s: 1.00
0.80		#1s: 20		Frac 1s: 1.00
0.90		#1s: 20		Frac 1s: 1.00
1.00		#1s: 20		Frac 1s: 1.00
```

**Comment by raver119** [comment]
Fixed. 100% this time :)
