### ISSUE TITLE
SameDiff - JVM crash with boolean OR operation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2514]
Reproducable using this test:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/gradcheck/GradCheckTransforms.java#L304-L438

Full crash log: https://gist.github.com/AlexDBlack/752096230bef75f559c902eb82457921

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1f22f6ee28, pid=11029, tid=0x00007f1f51a8c700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libnd4jcpu.so+0x473e28]  void functions::pairwise_transforms::PairWiseTransform<double>::exec<simdOps::Or<double> >(double*, long long, double*, long long, double*, long long, double*, long long)+0x258
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/alex/DL4J/nd4j/nd4j-backends/nd4j-tests/hs_err_pid11029.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by raver119** [comment]
Hypothetically fixed here: https://github.com/deeplearning4j/nd4j/pull/2522

**Comment by AlexDBlack** [comment]
I'm still seeing this (same error by the looks of it) with or/and/xor.
I've also added some and/xor tests here: https://github.com/deeplearning4j/nd4j/pull/2523

Should be possible to reproduce with all using those gradient checks.

**Comment by raver119** [comment]
Fixed once again. Same story: extraArgs are null on second (???) pass since different constructor was used. 

However, i'd like to know why op was called twice.

P.s. now it throws some NPE.

**Comment by AlexDBlack** [comment]
Tests now pass, thanks. NPE was due to lack of doDiff implementation.

**Comment by Liujish931** [comment]
i have the same issue how dit you fix it ?
