### ISSUE TITLE
SpecifiedIndex and put(): changes not reflected

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#611]
Due to the nature of SpecifiedIndex the following code is not working as intended:

```
public void testSliceAssign1() throws Exception {
        INDArray array = Nd4j.zeros(4, 4);

        INDArray patch = Nd4j.create(new float[] {1e-5f, 1e-5f, 1e-5f});

        INDArray slice = array.slice(1);
        int[] idx = new int[] {0,1,3};
        INDArrayIndex[] range = new INDArrayIndex[]{new SpecifiedIndex(idx)};

        INDArray subarray = slice.get(range);

        slice.put(range, patch );

        assertFalse(BooleanIndexing.and(array, Conditions.equals(0f)));
    }
```

That happens because INDArray.get(range) for SpecifiedIndex returns detached copy from original array, and not a view. So later put() updates detached copy, not original array.

Here's implemented fix, that forces put, without get() for such cases:
```
@Override
    public INDArray put(INDArrayIndex[] indices, INDArray element) {
        if (indices[0] instanceof SpecifiedIndex && element.isVector()) {
            indices[0].reset();
            int cnt = 0;
            while(indices[0].hasNext()) {
                int idx = indices[0].next();
                putScalar(idx, element.getDouble(cnt));
                cnt++;
            }
            return this;
        } else return get(indices).assign(element);
    }
```
If that's ok for everyone, it'll be merged later

**Comment by raver119** [comment]
Fixed and merged

**Comment by tkorach** [comment]
The error still exists for putScalar: 
In `BaseNDArray`:

`@Override
    public INDArray put(INDArrayIndex[] indices, Number element) {
        Nd4j.getCompressor().autoDecompress(this);
        INDArray get = get(indices);
        for (int i = 0; i < get.length(); i++)
            get.putScalar(i, element.doubleValue());
        return this;
    }
`
Here, the `get` is not a view but a detached copy, and therefore the changes done in `get.putScalar` is not propagated to the original array. 

`INDArray original = ...;
original.put(INDArrayIndex[] indices, INDArray element)` 
does solve the issue by copying item-by-item from the element array to the original array, but requires `element` to be of the same size as the original array - which could waste RAM: 
` val a1 = Nd4j.arange(12.0).reshape(2L, 3, 2).castTo(DataType.INT16);
    println("Original")
    println(a1);
    val indices = arrayOf(all(), indices(0, 2), point(1))
    a1.put(indices, Nd4j.onesLike(a1).muli(-1).castTo(DataType.INT16));
    println("a1.put(arrayOf(all(), indices(0,2), point(1)), Nd4j.onesLike(a1).muli(-1).castTo(DataType.INT16))");
    println(a1);
`
Is there a better solution?
